#!/bin/bash
#
# Copyright (C) 2011-2019 Aratelia Limited - Juan A. Rubio
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#
# Simple script to first purge and then re-install tizonia
#
# NOTE: Tizonia's Bintray repo must have been configured beforehand.
# https://bintray.com/tizonia
#

# Remove (purge) all tizonia packages and files
tizonia-apt-get-purge

# Clean apt-get cache
sudo apt-get clean

# Update and upgrade the system
sudo apt-get update \
    && sudo apt-get -y upgrade \
    && sudo apt-get -y dist-upgrade \
    && sudo apt-get -y autoremove

# Install tizonia packages
tizonia-apt-get-install
