#!/bin/bash
#
# Copyright (C) 2011-2014 Aratelia Limited - Juan A. Rubio
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#
# Simple MPRIS2-based remote control for tplay
#

if [[ $# -gt 2 ]]
then
    usage
    exit 1
fi

# Constants
readonly dbuscmd='dbus-send --print-reply --dest=org.mpris.MediaPlayer2.tplay /com/aratelia/tiz/tplay'
readonly mediaifc='org.mpris.MediaPlayer2'
readonly playerifc='org.mpris.MediaPlayer2.Player'
readonly propgetifc='org.freedesktop.DBus.Properties.Get'
readonly propsetifc='org.freedesktop.DBus.Properties.Set'

readonly canquitcmd='$dbuscmd $propgetifc string:"$mediaifc" string:"CanQuit"'
readonly canraisecmd='$dbuscmd $propgetifc string:"$mediaifc" string:"CanRaise"'
readonly hastracklistcmd='$dbuscmd $propgetifc string:"$mediaifc" string:"HasTrackList"'
readonly identitycmd='$dbuscmd $propgetifc string:"$mediaifc" string:"Identity"'
readonly urischemescmd='$dbuscmd $propgetifc string:"$mediaifc" string:"SupportedUriSchemes"'
readonly mimetypescmd='$dbuscmd $propgetifc string:"$mediaifc" string:"SupportedMimeTypes"'

readonly playstatuscmd='$dbuscmd $propgetifc string:"$playerifc" string:"PlaybackStatus"'
readonly loopstatusgetcmd='$dbuscmd $propgetifc string:"$playerifc" string:"LoopStatus"'
readonly ratecmd='$dbuscmd $propgetifc string:"$playerifc" string:"Rate"'
readonly shufflecmd='$dbuscmd $propgetifc string:"$playerifc" string:"Shuffle"'
readonly metadatacmd='$dbuscmd $propgetifc string:"$playerifc" string:"Metadata"'
readonly volumegetcmd='$dbuscmd $propgetifc string:"$playerifc" string:"Volume"'
readonly volumesetcmd='$dbuscmd $propsetifc string:"$playerifc" string:"Volume" variant:double:$2 &> /dev/null'

readonly playcmd='$dbuscmd $playerifc.Play   &> /dev/null'
readonly pausecmd="$dbuscmd $playerifc.Pause &> /dev/null"
readonly stopcmd='$dbuscmd $playerifc.Stop   &> /dev/null'
readonly nextcmd='$dbuscmd $playerifc.Next   &> /dev/null'
readonly prevcmd='$dbuscmd $playerifc.Previous   &> /dev/null'
readonly quitcmd='$dbuscmd $mediaifc.Quit   &> /dev/null'

function usage {
    echo "tizonia-remote. Copyright (C) 2014 Juan A. Rubio"
    echo "This software is part of Tizonia <http://tizonia.org>"
    echo
    echo "Usage : $0 <canquit|canraise|hastracklist|identity|urischemes|mimetypes..."
    echo "...|playstatus|loopstatus|rate|shuffle|metadata|volume|play|pause|stop|prev|next|quit|kill>"
}

function start_dbus {
    ## test for an existing bus daemon, just to be safe
    if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
        ## if not found, launch a new one
        export `dbus-launch --exit-with-session`
        echo "D-Bus per-session daemon address is: $DBUS_SESSION_BUS_ADDRESS"
        echo "D-Bus per-session daemon PID is    : $DBUS_SESSION_BUS_PID"
    fi
}

function main {
    start_dbus

    case "$1" in
        canquit)
            eval "$canquitcmd"  | sed 1d | cut -c26-
            ;;
        canraise)
            eval "$canraisecmd"  | sed 1d | cut -c26-
            ;;
        hastracklist)
            eval "$hastracklistcmd" | sed 1d | cut -c26-
            ;;
        identity)
            eval "$identitycmd" | sed 1d | cut -c25-
            ;;
        urischemes)
            eval "$urischemescmd" | sed 1,2d | sed '$ d' | cut -c17-
            ;;
        mimetypes)
            eval "$mimetypescmd" | sed 1,2d | sed '$ d' | cut -c17-
            ;;
        playstatus)
            eval "$playstatuscmd" | sed 1d | cut -c25-
            ;;
        loopstatus)
            eval "$loopstatusgetcmd" | sed 1d | cut -c25-
            ;;
        rate)
            eval "$ratecmd" | sed 1d | cut -c25-
            ;;
        shuffle)
            eval "$shufflecmd" | sed 1d | cut -c26-
            ;;
        metadata)
            eval "$metadatacmd" #| sed 1d | cut -c26-
            ;;
        volume)
            if [[ $# -eq 2 ]]
            then
                eval "$volumesetcmd"
            else
                eval "$volumegetcmd" | sed 1d | cut -c25-
            fi
            ;;
        play)
            eval "$playcmd"
            ;;
        pause)
            eval "$pausecmd"
            ;;
        stop)
            eval "$stopcmd"
            ;;
        prev)
            eval "$prevcmd"
            ;;
        next)
            eval "$nextcmd"
            ;;
        quit)
            eval "$quitcmd"
            ;;
        kill) echo  "Sending SIGKILL signal"
            killall -TERM tplay
            ;;
        *) echo "Unknown command"
            usage
            exit 1
            ;;
    esac

    exit $$
}

main "$@"
