#!/bin/bash
# Copyright (C) 2011-2015 Aratelia Limited - Juan A. Rubio
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Simple tail wrapper
#
# TODO: Generalize by taking the path to the tizonia log file as argument

tail -F ~/temp/tizonia.log.0 | cut -c 50- | sed 's/httpsrctrans.c//g' | sed 's/gmusicprc.c//g' | grcat conf.tizonia

# grep -E "debug_cback|socket_cback|write_cback|timer_cback" |
