name: tizonia
version: 0.10.0
summary: Tizonia command-line cloud music player.
description: |
  Command-line cloud music player for Linux with support for Spotify,
  Google Play Music, YouTube, SoundCloud and Dirble.
grade: stable
confinement: strict

apps:
  tizonia:
    command: ./bin/tizonia
    plugs:
      - home
      - network
      - network-bind
      - pulseaudio
      - process-control
      - alsa
      - removable-media

parts:
  pypideps:
    plugin: python
    python-version: python2
    python-packages:
      - soundcloud
      - gmusicapi
      - youtube-dl
      - pafy
      - pycountry
      - titlecase
    filesets:
      no-include:
        - -include
    stage:
      - $no-include
    prime:
      - $no-include

  tizonia:
    plugin: autotools
    source: https://github.com/tizonia/tizonia-openmax-il.git
    # source-tag: 0.7.0
    configflags: [--silent, --enable-silent-rules]
    build-packages:
      - build-essential
      - autoconf
      - autoconf-archive
      - automake
      - autotools-dev
      - libtool
      - libmad0-dev
      - liblog4c-dev
      - libasound2-dev
      - libdbus-1-dev
      - libdbus-c++-dev
      - libsqlite3-dev
      - libboost-all-dev
      - uuid-dev
      - libsdl1.2-dev
      - libvpx-dev
      - libmp3lame-dev
      - libfaad-dev
      - libev-dev
      - libtag1-dev
      - libfishsound1-dev
      - libmediainfo-dev
      - libcurl3
      - libcurl4-openssl-dev
      - libpulse-dev
      - libmpg123-dev
      - libvorbis-dev
      - libopus-dev
      - libopusfile-dev
      - libogg-dev
      - libflac-dev
      - liboggz2-dev
      - libsndfile1-dev
      - libspotify-dev
      - libffi-dev
      - libssl-dev
      - python-dev
      - python-setuptools
      - python-pip
      - python-decorator
      - python-protobuf
      - python-validictory
      - python-bs4
      - python-oauth2client
      - python-dateutil
      - python-mutagen
      - python-crypto
      - python-requests
      - curl
      - check
      - wget
      - sqlite3
      - dbus-x11
    after:
      - pypideps
    organize:
      ../installlib/python2.7/dist-packages: lib/python2.7/site-packages
    filesets:
      no-include:
        - -include
    stage:
      - $no-include
    prime:
      - $no-include

  env:
    plugin: nil
    stage-packages:
      - libmad0
      - liblog4c3
      - libasound2
      - libpulse0
      - libdbus-1-3
      - libdbus-c++-1-0v5
      - libdbus-c++-bin
      - libsqlite3-0
      - libboost-all-dev
      - uuid-runtime
      - libsdl1.2debian
      - libvpx3
      - libmp3lame0
      - libfaad2
      - libev4
      - libtag1v5
      - libfishsound1
      - libmediainfo0v5
      - libmpg123-0
      - libvorbis0a
      - libopus0
      - libopusfile0
      - libogg0
      - libflac8
      - liboggz2
      - libsndfile1
      - libspotify12
      - libcurl3
      - libffi6
      - sqlite3
      - dbus-x11
    filesets:
      no-include:
        - -include
      no-usr-lib-python2-dot-7:
        - -usr/bin/2to3-2.7
        - -usr/bin/pydoc2.7
        - -usr/lib/python2.7/UserString.py
        - -usr/lib/python2.7/base64.py
        - -usr/lib/python2.7/cProfile.py
        - -usr/lib/python2.7/cgi.py
        - -usr/lib/python2.7/encodings/rot_13.py
        - -usr/lib/python2.7/ensurepip/__init__.py
        - -usr/lib/python2.7/keyword.py
        - -usr/lib/python2.7/lib2to3/pgen2/token.py
        - -usr/lib/python2.7/mimify.py
        - -usr/lib/python2.7/pdb.py
        - -usr/lib/python2.7/platform.py
        - -usr/lib/python2.7/profile.py
        - -usr/lib/python2.7/pydoc.py
        - -usr/lib/python2.7/quopri.py
        - -usr/lib/python2.7/sitecustomize.py
        - -usr/lib/python2.7/smtpd.py
        - -usr/lib/python2.7/smtplib.py
        - -usr/lib/python2.7/symbol.py
        - -usr/lib/python2.7/tabnanny.py
        - -usr/lib/python2.7/test/pystone.py
        - -usr/lib/python2.7/test/regrtest.py
        - -usr/lib/python2.7/timeit.py
        - -usr/lib/python2.7/trace.py
        - -usr/lib/python2.7/uu.py
        - -usr/lib/python2.7/webbrowser.py
        - -usr/share/python/dh_python2
        - -usr/share/python/pyversions.py
    stage:
      - $no-include
      - $no-usr-lib-python2-dot-7
    prime:
      - $no-include
      - $no-usr-lib-python2-dot-7
    after:
      - tizonia
